import type { Article, Category, User, Comment, Tag, Like, Bookmark } from "./types"

export const mockCategories: Category[] = [
  {
    id: 1,
    name: "Politics",
    slug: "politics",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 2,
    name: "Technology",
    slug: "technology",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 3,
    name: "World",
    slug: "world",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 4,
    name: "Economy",
    slug: "economy",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 5,
    name: "Environment",
    slug: "environment",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 6,
    name: "Science",
    slug: "science",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 7,
    name: "Business",
    slug: "business",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const mockUsers: User[] = [
  {
    id: 1,
    email: "admin@newshub.com",
    name: "Elena Vance",
    role: "ADMIN",
    avatar: "/professional-woman-portrait.png",
    bio: "Head of Editorial with 15 years of experience in digital journalism.",
    email_verified_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 2,
    email: "editor@newshub.com",
    name: "Julian Marsh",
    role: "EDITOR",
    avatar: "/portrait-of-a-man-in-glasses.jpg",
    bio: "Specializing in technology and innovation news.",
    email_verified_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 3,
    email: "journalist@newshub.com",
    name: "Sarah Chen",
    role: "AUTHOR",
    avatar: "/portrait-of-a-woman-writing.jpg",
    bio: "Environment and science reporter focusing on sustainable solutions.",
    email_verified_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 4,
    email: "reader@newshub.com",
    name: "Alex Johnson",
    role: "READER",
    email_verified_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const mockTags: Tag[] = [
  { id: 1, name: "sustainability", slug: "sustainability" },
  { id: 2, name: "urban-planning", slug: "urban-planning" },
  { id: 3, name: "climate-action", slug: "climate-action" },
  { id: 4, name: "green-tech", slug: "green-tech" },
  { id: 5, name: "quantum-computing", slug: "quantum-computing" },
  { id: 6, name: "ai", slug: "ai" },
  { id: 7, name: "research", slug: "research" },
  { id: 8, name: "innovation", slug: "innovation" },
  { id: 9, name: "markets", slug: "markets" },
  { id: 10, name: "economics", slug: "economics" },
  { id: 11, name: "finance", slug: "finance" },
  { id: 12, name: "diplomacy", slug: "diplomacy" },
  { id: 13, name: "geopolitics", slug: "geopolitics" },
  { id: 14, name: "mergers", slug: "mergers" },
  { id: 15, name: "startups", slug: "startups" },
  { id: 16, name: "retail", slug: "retail" },
]

export const mockArticles: Article[] = [
  {
    id: 1,
    title: "The Future of Sustainable Cities: Reimagining Urban Life in 2026",
    slug: "future-of-sustainable-cities",
    content:
      "Urbanization is one of the defining trends of our century. As urban populations swell, planners are turning to innovative green technologies and circular economy principles to create resilient metropolises.",
    thumbnail: "/futuristic-green-city-with-solar-panels-and-vertic.jpg",
    status: "PUBLISHED",
    views: 12450,
    category_id: 5,
    author_id: 3,
    published_at: "2026-01-01T10:00:00Z",
    created_at: "2026-01-01T10:00:00Z",
    updated_at: "2026-01-01T10:00:00Z",
  },
  {
    id: 2,
    title: "Quantum Computing Breakthrough: Scientists Achieve Stable Qubit Entanglement",
    slug: "quantum-computing-breakthrough",
    content:
      "The promise of quantum computing has long been hampered by the fragility of qubits. A research team has successfully demonstrated a new method for stabilizing qubits at room temperature, bringing us closer to practical quantum advantage.",
    thumbnail: "/quantum-computer-processor-with-glowing-blue-light.jpg",
    status: "PUBLISHED",
    views: 8900,
    category_id: 2,
    author_id: 2,
    published_at: "2026-01-02T14:30:00Z",
    created_at: "2026-01-02T14:30:00Z",
    updated_at: "2026-01-02T14:30:00Z",
  },
  {
    id: 3,
    title: "Global Markets Rally Amidst Surprise Inflation Data",
    slug: "global-markets-rally",
    content:
      "Investors reacted with optimism this morning as the latest figures were released. Stock indices across Europe and Asia saw significant gains today after unexpected economic reports suggested a faster-than-expected cooling of inflation.",
    thumbnail: "/stock-market-chart-with-green-upward-trend-line.jpg",
    status: "PUBLISHED",
    views: 5600,
    category_id: 4,
    author_id: 1,
    published_at: "2026-01-03T09:15:00Z",
    created_at: "2026-01-03T09:15:00Z",
    updated_at: "2026-01-03T09:15:00Z",
  },
  {
    id: 4,
    title: "Diplomatic Breakthrough in Arctic Resource Dispute",
    slug: "arctic-resource-dispute-breakthrough",
    content:
      "The Arctic Council announced a landmark agreement late last night. After weeks of intense negotiations, major powers have reached a tentative agreement on maritime boundaries and resource extraction rights in the Arctic.",
    thumbnail: "/arctic-landscape-with-flags-of-different-nations.jpg",
    status: "PUBLISHED",
    views: 7200,
    category_id: 1,
    author_id: 1,
    published_at: "2026-01-04T08:00:00Z",
    created_at: "2026-01-04T08:00:00Z",
    updated_at: "2026-01-04T08:00:00Z",
  },
  {
    id: 5,
    title: "Tech Giants Announce Strategic Merger: A Game-Changer for the Industry",
    slug: "tech-giants-merger-announcement",
    content:
      "In a stunning move that has sent shockwaves through the tech industry, the companies announced their intentions today. Two of the world's largest technology companies have announced plans to merge, creating an industry powerhouse valued at over $500 billion.",
    thumbnail: "/quantum-computer-processor-with-glowing-blue-light.jpg",
    status: "PUBLISHED",
    views: 9800,
    category_id: 7,
    author_id: 2,
    published_at: "2026-01-05T11:45:00Z",
    created_at: "2026-01-05T11:45:00Z",
    updated_at: "2026-01-05T11:45:00Z",
  },
  {
    id: 6,
    title: "Startup Unicorn Disrupts Traditional Retail with AI-Powered Shopping",
    slug: "startup-unicorn-ai-retail",
    content:
      "The startup scene continues to evolve as new companies challenge traditional business models. A newly minted unicorn startup is revolutionizing the retail sector with cutting-edge AI technology that personalizes the shopping experience in real-time.",
    thumbnail: "/stock-market-chart-with-green-upward-trend-line.jpg",
    status: "PUBLISHED",
    views: 6400,
    category_id: 7,
    author_id: 3,
    published_at: "2026-01-06T13:20:00Z",
    created_at: "2026-01-06T13:20:00Z",
    updated_at: "2026-01-06T13:20:00Z",
  },
]

export const mockLikes: Like[] = [
  { id: 1, article_id: 1, user_id: 1 },
  { id: 2, article_id: 1, user_id: 2 },
  { id: 3, article_id: 2, user_id: 3 },
  { id: 4, article_id: 4, user_id: 2 },
  { id: 5, article_id: 5, user_id: 1 },
  { id: 6, article_id: 6, user_id: 2 },
]

export const mockBookmarks: Bookmark[] = [
  { id: 1, article_id: 1, user_id: 3 },
  { id: 2, article_id: 2, user_id: 1 },
  { id: 3, article_id: 2, user_id: 2 },
  { id: 4, article_id: 4, user_id: 1 },
  { id: 5, article_id: 5, user_id: 2 },
  { id: 6, article_id: 5, user_id: 3 },
]

export const mockComments: Comment[] = [
  {
    id: 1,
    article_id: 1,
    user_id: 2,
    content:
      "This is a fascinating look at the future. I'm particularly interested in the waste-to-energy integration mentioned.",
    status: "APPROVED",
    created_at: "2026-01-01T15:00:00Z",
    updated_at: "2026-01-01T15:00:00Z",
  },
  {
    id: 2,
    article_id: 1,
    user_id: 3,
    content:
      "Great article! I believe urban sustainability is the key to our future. We need more projects like these.",
    status: "APPROVED",
    created_at: "2026-01-01T16:30:00Z",
    updated_at: "2026-01-01T16:30:00Z",
  },
  {
    id: 3,
    article_id: 1,
    user_id: 1,
    parent_id: 2,
    content: "Completely agree with you on that point!",
    status: "APPROVED",
    created_at: "2026-01-01T17:00:00Z",
    updated_at: "2026-01-01T17:00:00Z",
  },
  {
    id: 4,
    article_id: 2,
    user_id: 2,
    content:
      "The implications of this breakthrough are staggering. If they can maintain this at room temperature, we're looking at a revolution.",
    status: "APPROVED",
    created_at: "2026-01-02T16:00:00Z",
    updated_at: "2026-01-02T16:00:00Z",
  },
  {
    id: 5,
    article_id: 2,
    user_id: 3,
    parent_id: 4,
    content: "When will this be available commercially?",
    status: "APPROVED",
    created_at: "2026-01-02T17:30:00Z",
    updated_at: "2026-01-02T17:30:00Z",
  },
  {
    id: 6,
    article_id: 3,
    user_id: 1,
    content: "This is why diversification is important. Markets are responding well to the news.",
    status: "PENDING",
    created_at: "2026-01-03T10:00:00Z",
    updated_at: "2026-01-03T10:00:00Z",
  },
]
